#!/usr/bin/env python3
"""
generate_symbol_sets.py
Generates per-symbol .set files for the OrderBlock EA.

Usage:
    python3 generate_symbol_sets.py [--template OBInclude/SetFiles/claude.set] [--out OBInclude/SetFiles/]

For each symbol, the script:
  - Copies the template .set file
  - Overrides symbol-specific parameters (magic number, news pair, max spread, etc.)
  - Saves as OBInclude/SetFiles/<SYMBOL>.set

After generating, load the appropriate .set file when attaching the EA to each chart.
"""
import codecs, argparse, os, copy, re

TEMPLATE_PATH = "OBInclude/SetFiles/claude.set"
OUT_DIR       = "OBInclude/SetFiles/"

# -------------------------------------------------------------------
# Per-symbol overrides
# key = MT5 symbol name (as shown in Market Watch)
# magic_offset: added to base magic number (keeps EA instances separate)
# npair:        news filter currencies (comma-separated)
# max_spread:   inpMaxSpread in points (0 = disabled)
#               Forex: 1 pip = 10 points on 5-digit broker
#               Metals/Indices: broker-dependent
# -------------------------------------------------------------------
SYMBOLS = {
    # ----- Forex majors -----
    "EURUSD": {"magic_offset":  1, "npair": "EUR",     "max_spread":  30},
    "GBPUSD": {"magic_offset":  2, "npair": "GBP",     "max_spread":  40},
    "USDJPY": {"magic_offset":  3, "npair": "USD,JPY",  "max_spread":  30},
    "AUDUSD": {"magic_offset":  4, "npair": "AUD",     "max_spread":  30},
    "USDCAD": {"magic_offset":  5, "npair": "USD,CAD",  "max_spread":  30},
    "USDCHF": {"magic_offset":  6, "npair": "USD,CHF",  "max_spread":  30},
    "NZDUSD": {"magic_offset":  7, "npair": "NZD",     "max_spread":  35},
    # ----- Forex crosses -----
    "EURGBP": {"magic_offset": 10, "npair": "EUR,GBP",  "max_spread":  30},
    "EURJPY": {"magic_offset": 11, "npair": "EUR,JPY",  "max_spread":  50},
    "GBPJPY": {"magic_offset": 12, "npair": "GBP,JPY",  "max_spread":  60},
    "AUDJPY": {"magic_offset": 13, "npair": "AUD,JPY",  "max_spread":  50},
    # ----- Metals -----
    "XAUUSD": {"magic_offset":  0, "npair": "USD",      "max_spread":   0},  # gold — existing
    "XAGUSD": {"magic_offset": 20, "npair": "USD",      "max_spread":   0},
    # ----- Indices -----
    "NAS100": {"magic_offset": 30, "npair": "USD",      "max_spread":   0},
    "US500":  {"magic_offset": 31, "npair": "USD",      "max_spread":   0},
    "US30":   {"magic_offset": 32, "npair": "USD",      "max_spread":   0},
    "GER40":  {"magic_offset": 33, "npair": "EUR",      "max_spread":   0},
    "UK100":  {"magic_offset": 34, "npair": "GBP",      "max_spread":   0},
    # ----- Crypto (if available) -----
    "BTCUSD": {"magic_offset": 40, "npair": "USD",      "max_spread":   0},
}

BASE_MAGIC = 1234555


def load_set(path):
    with codecs.open(path, "r", "utf-16") as f:
        return f.read()


def save_set(path, content):
    with codecs.open(path, "w", "utf-16") as f:
        f.write(content)


def set_param(content, key, value):
    """Replace the value of a parameter line in a .set file."""
    # Lines look like: key=val||...||N  or  key=val  (plain strings)
    pattern = re.compile(r"^(" + re.escape(key) + r"=)([^\r\n]*)", re.MULTILINE)
    m = pattern.search(content)
    if not m:
        return content  # param not found — skip silently
    old_rest = m.group(2)
    # If it has || separators, preserve them but update the first value
    if "||" in old_rest:
        parts = old_rest.split("||")
        parts[0] = str(value)
        new_rest = "||".join(parts)
    else:
        new_rest = str(value)
    return content[:m.start()] + m.group(1) + new_rest + content[m.end():]


def generate(template_content, symbol, overrides, base_magic):
    content = template_content
    magic   = base_magic + overrides["magic_offset"] * 10

    content = set_param(content, "uniqueMagicNumber", magic)
    content = set_param(content, "Npair",             overrides["npair"])
    content = set_param(content, "inpMaxSpread",      overrides["max_spread"])

    # Add a header comment
    header = f"; OrderBlock EA — per-symbol settings for {symbol}\n"
    header += f"; Generated by generate_symbol_sets.py\n"
    header += f"; magic={magic}  npair={overrides['npair']}  max_spread={overrides['max_spread']}\n;\n"

    # Replace the first line ("; saved automatically...") with our header
    lines  = content.split("\n")
    out    = []
    for i, line in enumerate(lines):
        if i == 0 and line.startswith("; saved"):
            out.extend(header.strip().split("\n"))
        else:
            out.append(line)
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description="Generate per-symbol .set files for OrderBlock EA")
    parser.add_argument("--template", default=TEMPLATE_PATH, help="Template .set file path")
    parser.add_argument("--out",      default=OUT_DIR,        help="Output directory")
    parser.add_argument("--symbols",  nargs="*",              help="Symbols to generate (default: all)")
    args = parser.parse_args()

    if not os.path.exists(args.template):
        print(f"ERROR: template not found: {args.template}")
        return

    os.makedirs(args.out, exist_ok=True)
    template = load_set(args.template)

    targets = args.symbols if args.symbols else list(SYMBOLS.keys())

    for sym in targets:
        if sym not in SYMBOLS:
            print(f"  SKIP {sym} — not in symbol map (add it to generate_symbol_sets.py)")
            continue
        out_path = os.path.join(args.out, f"{sym}.set")
        result   = generate(template, sym, SYMBOLS[sym], BASE_MAGIC)
        save_set(out_path, result)
        o = SYMBOLS[sym]
        print(f"  {sym:10s}  magic={BASE_MAGIC + o['magic_offset']*10}  npair={o['npair']:10s}  max_spread={o['max_spread']}  → {out_path}")

    print(f"\nDone. {len(targets)} set files written to {args.out}")
    print("\nUsage: attach OrderBlock EA to each symbol's chart and load the matching .set file.")


if __name__ == "__main__":
    main()
